#!/bin/sh
# This script changes sway's current colorscheme.
#
# It gets the theme from the command line or prompts the user to select one.
# After that, it notifies sway to apply the changes.
#
# To apply changes, instead of executing `swaymsg reload` to reload whole
# configuration, this script sources only the related configuration files and
# feeds the necessary commands to sway via `swaymsg -- <command>`. This
# significantly reduces the colorscheme changing latency.

if ! swaymsg >/dev/null 2>/dev/null; then
  exit
fi

SWAY_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/sway
SWAY_THEME_DIR=$SWAY_CONFIG_DIR/config.d/colorscheme


theme=$1
if [ -z "$theme" ]; then
  theme=$(cd "$SWAY_CONFIG_DIR/config.d"; find colorscheme -type f \
    | cut -d '/' -f 2 \
    | riced-menu)
fi

error_exit() {
  if command -v notify-send >/dev/null 2>&1; then
    notify-send --app-name "change-colorscheme" --urgency critical -- \
      "$1" "$2"
  else
      printf "%s: %s\n" "$1" "$2" >&2
  fi
  exit 1
}

if [ ! -f "$SWAY_CONFIG_DIR/config.d/colorscheme/$theme" ]; then
  error_exit "failed to change colorscheme" "colorscheme '$theme' doesn't exist"
fi

source_colorscheme() (
  while IFS= read -r line; do
    trimmed=${line#"${line%%[![:space:]]*}"}
    case $trimmed in
      '#'*)
        continue
        ;;
      '')
        continue
        ;;
    esac
    printf "%s;\0" "$trimmed"
  done | xargs -r0 -- swaymsg --
)

execute_commands() {
  while IFS= read -r line; do
    trimmed=${line#"${line%%[![:space:]]*}"}
    case $trimmed in
      '# DYNAMIC COMMAND END')
        return
        ;;
      '#'*)
        continue
        ;;
      '')
        continue
        ;;
    esac

    printf "%s;\0" "$trimmed"
  done | xargs -r0 -- swaymsg --
}

execute_bar_colors_commands() (
  bar_ids=$(swaymsg -rt get_bar_config | jq -r '.[]')

  while IFS= read -r line; do
    trimmed=${line#"${line%%[![:space:]]*}"}
    case $trimmed in
      '# BAR COLORS DYNAMIC COMMAND END')
        return
        ;;
      '#'*)
        continue
        ;;
      '')
        continue
        ;;
    esac
    for bar_id in $bar_ids; do
      printf "bar %s colors %s;\0" "$bar_id" "$trimmed"
    done
  done | xargs -r0 -- swaymsg --
)

# Source colorscheme
if ! source_colorscheme <"$SWAY_THEME_DIR/$theme";  then
  error_exit "failed to source colorscheme file: $SWAY_THEME_DIR/$theme"
fi

# Read and execute commands from visual config to set colors
while IFS= read -r line; do
  trimmed=${line#"${line%%[![:space:]]*}"}
  case $trimmed in
    '# DYNAMIC COMMAND BEGIN')
      if ! execute_commands; then
        error_exit "failed to execute command"
      fi
      ;;
    '# BAR COLORS DYNAMIC COMMAND BEGIN')
      if !execute_bar_colors_commands; then
        error_exit "failed to execute bar colors command"
      fi
      ;;
  esac
done <"$SWAY_CONFIG_DIR/config.d/visual"
