#!/bin/sh

wallpaper_dir=$(xdg-user-dir PICTURES)/wallpaper

imgfile=$(find "$wallpaper_dir" -type f -print0 \
  | xargs -0 swayimg -g -e "swayimg.enable_overlay = false" --; \
  echo x)
imgfile=${imgfile%x}

escaped=$(printf "%sx\n" "$imgfile" | sed 's/./\\&/g')
escaped=${escaped%\\x}

if [ -z "$imgfile" ]; then
  exit 0
fi

swaymsg -- output '*' bg "$escaped" stretch

if [ "$1" = "--persist" ]; then
  ln -sf -- "$imgfile" "$wallpaper_dir/current"
fi
