#!/bin/sh

: "${XDG_STATE_HOME:=$HOME/.local/state}"
COLOR_THEME_FILE=$XDG_STATE_HOME/colorscheme/sway/colorscheme

if [ -f "$COLOR_THEME_FILE" ] && [ -r "$COLOR_THEME_FILE" ]; then
  printf "%s\n" "${XDG_CONFIG_HOME:-$HOME/.config}/sway/config.d/colorscheme/$(cat -- "$COLOR_THEME_FILE")"
else
  printf "/dev/null"
fi
