#!/bin/sh

opt_prompt=
opt_list=
while getopts "lp:" opt; do
  case $opt in
    l)
      opt_list=1
      ;;
    p)
      opt_prompt=$OPTARG
      ;;
    \?)
      exit 2
      ;;
  esac
done

mark=$({ [ -n "$opt_list" ] && swaymsg -rt get_marks || printf "[]"; } \
  | jq -r '.[]' \
  | menu-wrapper dmenu -p "$opt_prompt") || exit 

case $mark in
  *[!-_+=\ a-z0-9]*)
    summary=$(i18n -n sway-scripts "Invalid mark")
    body=$(i18n -n sway-scripts "Mark should have pattern: [-_+=\ a-z0-9]+")
    notify-or-print -en "get-mark" -- "$summary" "$body"
    exit 1
    ;;
esac

printf "%s\n" "$mark"
