#!/bin/sh

picdir=$(xdg-user-dir PICTURES)
wallpaper_dir=$picdir/wallpaper

set -- "$wallpaper_dir"/*
index=$(awk -v seed="$(date +%Y%m%d%H%M%S)" -v max="$#" '
BEGIN {
  srand(seed);
  print(int(rand() * max));
}')

file=$(eval 'printf "%sx" "${'"$index"'}"')
file=${file%x}
exec swaylock -i ":$file" --font sans-serif --font-size 14
