#!/bin/sh

PROMPT=$(i18n -n sway-scripts "Move marked window to this workspace: ")
mark=$(run-sway-script get-mark -lp "$PROMPT") || exit

swaymsg -- "[con_mark=\"$mark\"] move to workspace current, focus"
