#!/bin/sh

PROMPT=$(i18n -n sway-scripts "Move to workspace: ")

workspace=$(swaymsg -rt get_workspaces \
  | jq -r '.[].name' \
  | menu-wrapper dmenu -p "$PROMPT")

swaymsg -- move container to workspace "$workspace"
