#!/bin/sh

opt_persist=
while getopts "p" opt; do
  case $opt in
    p)
      opt_persist=1
      ;;
    \?)
      exit 2
      ;;
  esac
done

shift "$((OPTIND - 1))"

[ "$#" -eq 0 ] && exit 0

imgfile=$1
escaped=$(printf "%sx\n" "$imgfile" | sed 's/./\\&/g')
escaped=${escaped%\\x}

case $imgfile in
  *$'\n'*)
    printf "image pathname can not contain newline\n" >&2
    exit 1
    ;;
esac

swaymsg -q -- output '*' bg "$escaped" stretch >/dev/null 2>&1 || true

if [ -n "$opt_persist" ]; then
  ln -sf -- "$imgfile" "$(get-sway-state -c current-wallpaper)"
fi
