#!/bin/sh

PROMPT="Workspace: "
[ "$LANG" = zh_CN.UTF-8 ] && PROMPT="切换到工作区："

workspace=$(swaymsg -rt get_workspaces \
  | jq -r '.[].name' \
  | menu-wrapper dmenu -p "$PROMPT")

swaymsg -- workspace "$workspace"
