#!/bin/sh
# This script changes sway's current colorscheme.
#
# It gets the theme from the command line or prompts the user to select one.
# After that, it notifies sway to apply the changes.
#
# To apply changes, instead of executing `swaymsg reload` to reload whole
# configuration, this script sources only the related configuration files and
# feeds the necessary commands to sway via `swaymsg -- <command>`. This
# significantly reduces the colorscheme changing latency.

if ! swaymsg >/dev/null 2>/dev/null; then
  exit
fi

SWAY_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/sway
SWAY_THEME_DIR=$SWAY_CONFIG_DIR/config.d/colorscheme


theme=$1
if [ -z "$theme" ]; then
  theme=$(cd "$SWAY_CONFIG_DIR/config.d"; find colorscheme -type f \
    | cut -d '/' -f 2 \
    | menu-wrapper dmenu)
fi

error_exit() {
  if command -v notify-send >/dev/null 2>&1; then
    notify-send --app-name "switch-colorscheme" --urgency critical -- \
      "$1" "$2"
  else
      printf "%s: %s\n" "$1" "$2" >&2
  fi
  exit 1
}

if [ ! -f "$SWAY_CONFIG_DIR/config.d/colorscheme/$theme" ]; then
  error_exit "failed to change colorscheme" "colorscheme '$theme' doesn't exist"
fi

flatten_sway_config_commands() {
  # Without IFS= ,the leading and trailing spaces are trimmed out by shell
  while read -r line; do
    case $line in
      '#'*|'')
        continue
        ;;
      '}')
        break
        ;;
      *' {')
        if ! flatten_sway_config_commands "$1${line%"{"}"; then
          return 1
        fi
        ;;
      *)
        printf "%s\n" "$1$line"
        ;;
    esac
  done
}

make_nul_terminated() {
  while IFS= read -r cmd; do
    printf "%s;\0" "$cmd"
  done
}

source_sway_config_runtime() {
  flatten_sway_config_commands \
    | make_nul_terminated \
    | xargs -r0 -- swaymsg --
}

source_sway_config_runtime <"$SWAY_CONFIG_DIR/config.d/colorscheme/$theme"
