#!/bin/sh

has_display() {
  [ -n "$DISPLAY$WAYLAND_DISPLAY" ]
}

error_exit() {
  if has_display && command -v notify-send >/dev/null 2>&1; then
    notify-send --urgency=critical -- "$1" "$2" >&2
  else
    printf "%s: %s\n" "$1" "$2"
  fi

  exit 1
}

opt_persist=false
while getopts "p" opt; do
  case $opt in
    p)
      opt_persist=true
      ;;
    \?)
      exit 2
      ;;
  esac
done

shift "$((OPTIND - 1))"

picdir=$(xdg-user-dir PICTURES)
wallpaper_dir=$picdir/wallpaper

if [ "$#" -eq 0 ]; then
  imgfile=$(swayimg -g -e "swayimg.enable_overlay = false" -- "$wallpaper_dir"; echo x)
  imgfile=${imgfile%x}
else
  imgfile="$1"
fi

case $imgfile in
  *$'\n'*)
    if [ "$LANG" = zh_CN.UTF-8 ]; then
      title="不支持的路径名" 
      body="所选取的文件的路径中不能包含换行符"
    else
      title="unsupported pathname"
      body="Pathnames containing newlines are not supported"
    fi
    error_exit "$title" "$body"
    ;;
esac

escaped=$(printf "%sx\n" "$imgfile" | sed 's/./\\&/g')
escaped=${escaped%\\x}

if [ -z "$imgfile" ]; then
  exit 0
fi

if swaymsg -q >/dev/null 2>&1; then
  swaymsg -- output '*' bg "$escaped" stretch
fi

if [ "$opt_persist" = true ]; then
  ln -sf -- "$imgfile" "$picdir/sway-current-wallpaper"
fi
