#!/bin/sh

opt_persist=
while getopts "p" opt; do
  case $opt in
    p)
      opt_persist=1
      ;;
    \?)
      exit 2
      ;;
  esac
done

shift "$((OPTIND - 1))"

wallpaper_dir=$(xdg-user-dir PICTURES)/wallpaper

if [ "$#" -eq 0 ]; then
  imgfile=$(swayimg -g -e "swayimg.overlay = false" -- "$wallpaper_dir"; echo x)
  imgfile=${imgfile%x}
else
  imgfile="$1"
fi

case $imgfile in
  *$'\n'*)
    notify-or-print -en switch-wallpaper -- \
      "$(i18n -n sway-scripts "Unsupported pathname")" \
      "$(i18n -n sway-scripts "Pathnames containing newlines are not supported")"
    exit 1
    ;;
esac

[ -z "$imgfile" ] && exit 0

set -- -- "$imgfile"
[ -n "$opt_persist" ] && set -- -p "$@"
run-sway-script set-wallpaper "$@"
