#!/bin/sh
# This script changes sway's current colorscheme.
#
# It gets the theme from the command line or prompts the user to select one.
# After that, it notifies sway to apply the changes.
#
# To apply changes, instead of executing `swaymsg reload` to reload whole
# configuration, this script sources only the related configuration files and
# feeds the necessary commands to sway via `swaymsg -- <command>`. This
# significantly reduces the colorscheme changing latency.

if ! swaymsg >/dev/null 2>/dev/null; then
  exit
fi

SWAY_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/sway
SWAY_THEME_DIR=$SWAY_CONFIG_DIR/colorscheme


theme=$1
if [ -z "$theme" ]; then
  theme=$(cd "$SWAY_CONFIG_DIR"; find colorscheme -type f \
    | cut -d '/' -f 2 \
    | menu-wrapper dmenu)
fi

if [ ! -f "$SWAY_CONFIG_DIR/colorscheme/$theme" ]; then
  notify-or-print -en switch-colorscheme -- \
    "$(i18n -n sway-scripts "Failed to switch colorscheme")" \
    "$(i18n -n sway-scripts "Color scheme '\$1' doesn't exist" "$theme")"
  exit 1
fi

make_nul_terminated() {
  while IFS= read -r cmd; do
    printf "%s;\0" "$cmd"
  done
}

source_sway_config_runtime() {
  run-sway-script flatten-config-commands \
    | make_nul_terminated \
    | xargs -r0 -- swaymsg --
}

source_sway_config_runtime <"$SWAY_CONFIG_DIR/colorscheme/$theme"
