#!/usr/bin/env bash

shopt -s extglob

IMAGES=()
MEDIA=()
TEXTS=()
DIRS=()
OTHERS=()

xdg_open_files() {
  for f; do
    nohup xdg-open "$f" </dev/null &>/dev/null &
  done
}

myrealpath() {
  link="$1"
  while [ -L "$link" ]; do
    target=$(readlink -- "$link"; echo x)
    target=${target%$'\n'x}
    case $target in
      /*)
        link=$target
        ;;
      *)
        dir=$(dirname -- "$link"; echo x)
        link=${dir%$'\n'x}/$target
        ;;
    esac
  done

  printf "%s" "$link"
}

for f in "$@"; do
  if [ -L "$f" ]; then
    f=$(myrealpath "$f"; echo x)
    f=${f%x}
  fi
  case $(file --brief --mime-type -- "$f" 2>/dev/null) in
    image/*)
      IMAGES+=("$f")
      ;;
    @(audio|video)/*)
      MEDIA+=("$f")
      ;;
    @(application/@(json|yaml|toml)|text/*))
      TEXTS+=("$f")
      ;;
    inode/directory)
      DIRS+=("$f")
      ;;
    *)
      OTHERS+=("$f")
      ;;
  esac
done

if [ ${#DIRS[@]} -ne 0 ]; then
  if [ ${#IMAGES[@]} -ne 0 ]; then
    IMAGES+=("${DIRS[@]}")
  elif [ ${#TEXTS[@]} -ne 0 ]; then
    TEXTS+=("${DIRS[@]}")
  else
    OTHERS+=("${DIRS[@]}")
  fi
fi

if [ ${#IMAGES[@]} -ne 0 ]; then
  if type -P swayimg &>/dev/null; then
    flags=
    # Gallary mode for multiple images
    [ ${#IMAGES[@]} -gt 1 ] && flags="$flags -g"

    # Recursively scan for images if there is a directory
    for image in "${IMAGES[@]}"; do
      if [ -d "$image" ]; then
        flags="$flags -r"
        break
      fi
    done

    swayimg $flags -- "${IMAGES[@]}" </dev/null &>/dev/null &
  else
    xdg_open_files "${IMAGES[@]}"
  fi
fi

if [ ${#MEDIA[@]} -ne 0 ]; then
  if type -P mpv &>/dev/null; then
    mpv -- "${MEDIA[@]}" </dev/null &>/dev/null &
  else
    xdg_open_files "${MEDIA[@]}"
  fi
fi

if [ ${#OTHERS[@]} -ne 0 ]; then
  xdg_open_files "${OTHERS[@]}"
fi

if [ ${#TEXTS[@]} -ne 0 ]; then
  ${EDITOR:-vim} -- "${TEXTS[@]}" </dev/null 2>/dev/null
fi
