#!/bin/sh

xdg_open_files() {
  for f; do
    nohup xdg-open "$f" </dev/null &>/dev/null &
  done
}

open_images() {
  count=$#
  while [ "$count" -ne 0 ]; do
    count=$((count - 1))
    f=$1
    shift

    case $(file --brief --mime-type -- "$f" 2>/dev/null) in
      image/*)
        set -- "$@" "$f"
        ;;
    esac
  done

  if [ "$#" -eq 0 ]; then
    return 0
  fi

  if command -v swayimg >/dev/null 2>&1; then
    flags=
    # Gallary mode for multiple images
    [ "$#" -gt 1 ] && flags="$flags -g"
    swayimg $flags -- "$@" </dev/null >/dev/null 2>&1 &
  else
    xdg_open_files "$@"
  fi
}

open_media() {
  count=$#
  while [ "$count" -ne 0 ]; do
    count=$((count - 1))
    f=$1
    shift

    case $(file --brief --mime-type -- "$f" 2>/dev/null) in
      audio/*|video/*)
        set -- "$@" "$f"
        ;;
    esac
  done

  if [ "$#" -eq 0 ]; then
    return 0
  fi


  if command -v mpv >/dev/null 2>&1; then
    mpv -- "$@" </dev/null >/dev/null 2>&1 &
  else
    xdg_open_files "$@"
  fi
}

open_text() {
  count=$#
  while [ "$count" -ne 0 ]; do
    count=$((count - 1))
    f=$1
    shift

    case $(file --brief --mime-type -- "$f" 2>/dev/null) in
      application/json|\
      application/yaml|\
      application/toml|\
      application/mbox|\
      text/*)
        set -- "$@" "$f"
        ;;
    esac
  done

  if [ "$#" -eq 0 ]; then
    return 0
  fi

  if command -v "${EDITOR:=vim}" >/dev/null 2>&1; then
    "$EDITOR" -- "$@"
  else
    xdg_open_files "$@"
  fi
}

open_others() {
  count=$#
  while [ "$count" -ne 0 ]; do
    count=$((count - 1))
    f=$1
    shift

    case $(file --brief --mime-type -- "$f" 2>/dev/null) in
      image/*|audio/*|video/*|text/*|\
      application/json|\
      application/yaml|\
      application/toml|\
      application/mbox)
        continue
        ;;
      *)
        set -- "$@" "$f"
        ;;
    esac
  done

  xdg_open_files "$@"
}

myrealpath() {
  link="$1"
  while [ -L "$link" ]; do
    target=$(readlink -- "$link"; echo x)
    target=${target%$'\n'x}
    case $target in
      /*)
        link=$target
        ;;
      *)
        dir=$(dirname -- "$link"; echo x)
        link=${dir%$'\n'x}/$target
        ;;
    esac
  done

  printf "%s" "$link"
}

# Resolve symbolic links
count=$#
while [ "$count" -ne 0 ]; do
  count=$((count - 1))
  f=$1
  shift

  if [ -L "$f" ]; then
    f=$(myrealpath "$f"; echo x)
    f=${f%x}
  fi
  set -- "$@" "$f"
done

open_images "$@"
open_media "$@"
open_text "$@"
open_others "$@"
