#!/usr/bin/env bash

shopt -s extglob

file=$1
mime_type=$(file --mime-type --brief -- "$file" </dev/null)

case "$mime_type" in
  @(application/@(yaml|toml|json)|text/*))
    termcolor=$(termcolors)
    if [ "$termcolor" -eq 16777216 ]; then
      output_format=truecolor
    else
      output_format=ansi
    fi
    highlight -O "$output_format" -- "$file"
    ;;
  *)
    content=$(file --brief -- "$file")
    length=${#content}
    width=$(($2 - 3))
    if [ "$width" -le 0 ]; then
      exit
    fi
    for ((i = 0; i < length; i += this_width)); do
      this_width=$((i + width < length ? width : length - i))
      printf "%s\n" "${content:$i:$this_width}"
    done
    ;;
esac
