#!/bin/sh

file=$1
mime_type=$(file --mime-type --brief -- "$file" </dev/null)

case "$mime_type" in
  application/yaml|\
  application/toml|\
  application/json|\
  application/mbox|\
  text/*)
    termcolor=$(termcolors)
    if [ "$termcolor" -eq 16777216 ]; then
      output_format=truecolor
    else
      output_format=ansi
    fi
    highlight -O "$output_format" -- "$file"
    ;;
  *)
    file --brief -- "$file" | fold -sw "$2"
    ;;
esac
