#!/usr/bin/env bash

shopt -s extglob

file=$1
mime_type=$(file --mime-type --brief -- "$file" </dev/null)

case "$mime_type" in
  @(application/@(yaml|toml|json)|text/*))
    termcolor=$(termcolors)
    if [ "$termcolor" -eq 16777216 ]; then
      output_format=truecolor
    else
      output_format=ansi
    fi
    highlight -O "$output_format" -- "$file"
    ;;
  *)
    file --brief -- "$file" | fold -sw "$2"
    ;;
esac
