#!/bin/sh

# Assume that there are no empty line
make_result() {
  IFS= read -r line
  if [ -z "$line" ]; then
    printf "%s\n" "No matchs found"
    exit 1
  else
    printf "%s\n" "Found"
    printf "%s\n" "$line"
    exec cat
  fi
}

make_input() {

  if ! run-neomutt-script -e get-addressbook; then
    return
  fi
  run-neomutt-script get-addressbook
}

make_input | fuzzy-query "$1" 2>/dev/null | make_result
