#!/bin/sh

# Assume that there are no empty line
make_result() {
  IFS= read -r line
  if [ -z "$line" ]; then
    printf "%s\n" "No matchs found"
    exit 1
  else
    printf "%s\n" "Found"
    printf "%s\n" "$line"
    exec cat
  fi
}

make_input() {
  get_addrbook=${XDG_CONFIG_HOME:-$HOME/.config}/neomutt/scripts/get-addressbook
  if [ ! -f "$get_addrbook" ]; then
    return
  fi

  if [ -x "$get_addrbook" ]; then
    "$get_addrbook"
  else
    sh -- "$get_addrbook"
  fi
}

make_input | fuzzy-query "$1" 2>/dev/null | make_result
