#!/bin/sh

case $(termcolors) in
  16777216|256)
    ;;
  *)
    echo none
    exit
    ;;
esac

: "${XDG_STATE_HOME:=$HOME/.local/state}"
COLOR_THEME_FILE=$XDG_STATE_HOME/colorscheme/neomutt/colorscheme

if [ ! -r "$COLOR_THEME_FILE" ]; then
  printf "none\n"
  exit
fi

printf "256-%s\n" "$(cat -- "$COLOR_THEME_FILE")"
