#!/bin/sh

case $(termcolors) in
  16777216|256)
    ;;
  *)
    printf "none\n"
    exit
    ;;
esac

colorscheme_state=$(get-config-state -cp neomutt/state current-colorscheme)

if [ ! -r "$colorscheme_state" ]; then
  printf "none\n"
  exit
fi

printf "256-%s\n" "$(cat -- "$colorscheme_state")"
