#!/bin/sh

if [ -n "$DISPLAY$WAYLAND_DISPLAY" ] && command -v notify-send >/dev/null 2>&1; then
  notify-send --icon=/usr/share/neomutt/logo/neomutt.svg --category email.arrived -- \
    "$(i18n -n neomutt "New Email")" \
    "$(i18n -n neomutt '$1 new messages, $2 unread.' "$1" "$2")" 1>/dev/null 2>&1
else
  ring-bell message-new-email 1>/dev/null 2>&1
fi
